apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pl95whwba-python
  janus-idp.io/tekton: pl95whwba-python
  backstage.io/kubernetes-id: pl95whwba-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pl95whwba-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
